config/routes.rb
Challenge::Application.routes.draw do

  get "users/dashboard"
  get "users/:id/events" => "users#events", :as => "user_events"

  devise_for :users

  root :to => "users#dashboard"

  resources :activities, :only => [:index]
  resources :events, :only => [:create, :destroy]

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  has_many :users, :through => :events
  has_many :events

  def score_for_user_and_date(user,date)
    gross_score = events.where(:user_id => user.id, :completed_date => date).map{ |event| event.count*self.value }.sum
    unless name == "alcohol"
      hundreds = gross_score/100
      adjusted_score = 0
      (hundreds+1).times do
        if gross_score > 100
          adjusted_score = adjusted_score + 100
          gross_score = (gross_score - 100)/2
        else
          adjusted_score = adjusted_score + gross_score
          gross_score = 0
        end
      end
      adjusted_score
    else
      gross_score
    end
  end

end

app/models/day.rb
class Day < ActiveRecord::Base

  belongs_to :user

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :activity
  belongs_to :user

  validates_presence_of :user, :activity, :count, :completed_date

  after_save :update_score
  after_destroy :update_score

  def update_score
    day = user.days.find_or_create_by_date(completed_date)
    day.score = user.points_for_date(completed_date)
    day.save
  end


end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :trackable

  has_many :events
  has_many :activities, :through => :events
  has_many :days

  validates_presence_of :first_name, :last_name, :email

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :first_name, :last_name

  def self.challenge_day
    ((Time.now.utc + Time.zone_offset('CST')).to_date - Settings.start_date.to_date).to_i + 1
  end

  def total_points
    days.map(&:score).sum
  end

  def todays_points
    points_for_date((Time.now.utc + Time.zone_offset('CST')).to_date)
  end

  def daily_average
    daily_scores = days.map(&:score)
    daily_scores.inject{ |sum, el| sum + el }.to_f / User.challenge_day
  end

  def points_for_date(date)
    score = 0
    Activity.all.each do |activity|
      score += activity.score_for_user_and_date( self, date )
    end
    score
  end

end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = Activity.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def create
    @event = current_user.events.new(params[:event])
    if @event.save
      flash[:success] = "Event added!"
    else
      flash[:error] = "There was a problem saving the event"
    end
    redirect_to root_path
  end

  def destroy
    @event = current_user.events.find(params[:id])
    @event.destroy
    flash[:success] = "Event destroyed"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def dashboard
    if current_user
      @leaderboard_users = User.includes(:days).all.sort_by { |u| -u.total_points }
      @recent_events = current_user.events.order('created_at DESC').limit(5)
      @new_event = Event.new(:user => current_user)
    else
      render "not_signed_in"
    end
  end

  def events
    @user = User.find(params[:id])
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/activities/index.html.haml
%h1 Activities

%table.bordered-table.zebra-striped
  %thead
    %th Name
    %th Point Value
    %th Unit
    %th Notes
  - @activities.each do |activity|
    %tr
      %td= activity.name.titleize
      %td= activity.value
      %td= activity.unit ? activity.unit.titleize : "Each"
      %td= activity.notes

app/views/events/create.html.haml
%h1 Events#create
%p Find me in app/views/events/create.html.haml

app/views/layouts/_flashes.html.haml
.row
  #flashes.span6.offset7
    - flash.each do |key, value|
      .alert-message.fade.in( class="#{key} block-message" data-alert="alert" )
        %a.close{ :href=> "#" } ×
        %p= value

app/views/layouts/_footer.html.haml
%p Strength does not come from physical capacity. It comes from an indomitable will. -Mahatma Gandhi

app/views/layouts/_head.html.haml
%meta{ :charset => "utf-8" }/

-# Always force latest IE rendering engine (even in intranet) & Chrome Frame
-# Remove this if you use the .htaccess
%meta{ "http-equiv" => "X-UA-Compatible", :content => "IE=edge,chrome=1" }/

%title 100 Day Fitness Challenge

%meta{ :name => "description", :content => "" }/
%meta{ :name => "author", :content => "" }/

-# Mobile viewport optimized: j.mp/bplateviewport
%meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }/

-# Place favicon.ico and apple-touch-icon.png in the root directory: mathiasbynens.be/notes/touch-icons

-# Pass in a stylesheet_partial to render inside your head
- if local_assigns[:stylesheet_partial]
  = render local_assigns[:stylesheet_partial]

-# All JavaScript at the bottom, except for Modernizr and Respond.
-# Modernizr enables HTML5 elements & feature detects; Respond is a polyfill for min/max-width CSS3 Media Queries
= javascript_include_tag 'head'
= csrf_meta_tag

app/views/layouts/_header.html.haml
.topbar
  .fill
    .container
      %h3
        %a.brand{:href => root_path}
          100 Day Challenge
          (Day #{User.challenge_day})
      %ul.nav
        - if current_user
          %li
            = link_to "Activities", activities_path
      .pull-right
        %ul.nav
          - if current_user
            %li
              = link_to "Sign Out", destroy_user_session_path, :method => 'delete'
          - else
            %li
              = link_to "Sign In", new_user_session_path
            %li
              = link_to "Sign Up", new_user_registration_path

app/views/layouts/_javascripts.html.haml
= javascript_include_tag 'application'

-#  Append your own using content_for :javascripts
= yield :javascripts

-# asynchronous google analytics: mathiasbynens.be/notes/async-analytics-snippet
-# Looks for google_account_id first in ENV['GOOGLE_ACCOUNT_ID'] then in config/google.yml
- if !google_account_id.blank?
  :javascript
    var _gaq=[["_setAccount","#{google_account_id}"],["_trackPageview"],["_trackPageLoadTime"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));

app/views/layouts/_stylesheets.html.haml
= stylesheet_link_tag 'application'

app/views/layouts/application.html.haml
!!! 5
-ie_html :class => 'no-js', :lang => 'en' do
  %head
    = render "layouts/head", :stylesheet_partial => "layouts/stylesheets"
  %body{ :class => "#{controller.controller_name} #{controller.action_name}" }
    %header
      = render "layouts/header"
    .container#main{ :role => 'main' }
      = render "layouts/flashes"
      = yield
      %footer
        = render "layouts/footer"
    = render "layouts/javascripts"

app/views/users/dashboard.html.haml
:javascript
  var units = #{'{' + Activity.all.map{|a| a.id.to_s + ': "' + (a.unit ? a.unit.pluralize : "") + '"'}.join(', ') + '}'};
.row
  .span10
    .row
      .span5
        %h2 Recent Activities
        - @recent_events.each do |event|
          %p
            = link_to "Again!", events_path(:event => {:completed_date => (Time.now.utc + Time.zone_offset('CST')).to_date, :activity_id => event.activity_id, :count => event.count }), :method => 'post', :class => 'btn success'
            #{pluralize(event.count, (event.activity.unit ? event.activity.unit : event.activity.name))}
            = " #{event.activity.unit ? event.activity.name : nil}"
      .span5
        %h2 Stats
        %p Today: #{current_user.todays_points}
        %p Daily Average: #{current_user.daily_average}
        %p Total points: #{current_user.total_points}

    .row
      .span9.well
        %h2 New Activity
        = simple_form_for @new_event, :wrapper => 'stacked', :html => { :class => 'form-stacked no_offset'} do |f|
          = f.association :activity, :collection => Activity.all, :prompt => "Which Activity?", :label => false
          %label
            How many
            %span#miles-minutes
            ?
          = f.input :count, :label => false
          %br
          = f.input :completed_date, :label => "Date (Today is default)", :default => Time.now.in_time_zone("Central Time (US & Canada)").to_date
          = f.button :submit, :class => 'primary'

  .span10
    %h2 Leaderboard
    %table.bordered-table.zebra-striped
      %thead
        %th Rank
        %th User
        %th Points
      - @leaderboard_users.each_with_index do |user, index|
        %tr
          %td= index+1
          %td= link_to "#{user.first_name} #{user.last_name}", user_events_path(:id => user.id)
          %td= user.days.map(&:score).sum

app/views/users/events.html.haml
%h1= "#{@user.first_name} #{@user.last_name}"
%h3 Recent Activities
- @user.events.order('created_at DESC').limit(40).each do |event|
  %p
    #{pluralize(event.count, (event.activity.unit ? event.activity.unit : event.activity.name))}
    = " #{event.activity.unit ? event.activity.name : nil}"
    on #{event.completed_date.to_s}
    - if current_user == @user
      = link_to "Delete", event_path(event), :method => :delete, :confirm => "Are you sure?"

app/views/users/not_signed_in.html.haml
%h1 The next 100 day challenge is coming...
%p If you're super excited, click sign up in the upper right hand corner

app/views/users/show.html.haml
%h1= "#{@user.first_name} #{@user.last_name}"
%h3 Recent Activities
- @user.events.order('created_at DESC').limit(40).each do |event|
  %p
    #{pluralize(event.count, (event.activity.unit ? event.activity.unit : event.activity.name))}
    = " #{event.activity.unit ? event.activity.name : nil}"